version: "3.9"

services:
  database:
    image: postgres
    container_name: database_investimentos
    restart: always
    ports:
      - 65035:5432
    environment:
      - POSTGRES_USER=pjgmaaowbsumpf
      - POSTGRES_PASSWORD=4819723090675007f1c71c240989e62b42e80e016a77141eeb691cbb70a0ed21
      - POSTGRES_DB=dflh9fa000o3si
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: investimentos
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local